[project]
name = "deploydocus2"
version = "0.2.0"
description = ""
authors = [
    {name = "Partho Bhowmick",email = "p.s.bhowmick@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pydantic (>=2.10.6,<3.0.0)",
    "rich (>=14.0.0,<15.0.0)",
    "kubernetes-client-urllib3-pydantic (>=32.0.0,<35.0.0)"
]
license = "MIT"
dynamic = [ "classifiers" ]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Typing :: Typed",
    "Programming Language :: Python :: 3.13",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
]

[tool.poetry.group.dev.dependencies]
flake8 = ">=7.3.0"
mypy = ">=1.5,<2.0.0"
black = ">=25.1.0"
isort = ">=6.0.1,<7.0.0"
wheel = ">=0.45.1,<1.0.0"
cython = "^3.1.4"
flake8-pydantic = "^0.4.0"
setuptools = "^80.9.0"
pip = "^25.2"
pytest = "^8.4.2"
ipython = "^9.5.0"
python-devtools = "^2"
pyright = "^1.1.405"
datamodel-code-generator = "^0.33.0"
pyyaml = "^6.0.2"
pytest-cov = "^7.0.0"
types-pyyaml = "^6.0.12.20250915"

[tool.poetry.group.docs.dependencies]
mkdocs = ">=1.6.1,<2.0.0"
mkdocs-material = {extras = ["imaging"], version = ">=9.6.20,<10.0.0"}
mkdocstrings-python = "^1.18.2"
mkdocs-exclude = "^1.0.2"
mkdocs-redirects = "^1.2.2"
pymdown-extensions = "^10.16.1"
mkdocs-autorefs = "^1.4.3"
google-cloud-container = "^2.59.0"

[tool.black]
line-length = 88
target-version = ["py313"]

[tool.isort]
profile = "black"
